### PR TITLE
Update opentracing-api to 0.31.0

### PR DESCRIPTION
**Pull request by ygaller**

### CODE REVIEW

**Comment by ygaller** [comment]
@bhs Wondering if there's any chance you guys could align this project with the latest opentracing version. Thanks!

**Comment by tedsuo** [comment]
Hi @ygaller. LGTM, I've asked @malafeev to review as well.

**Comment by malafeev** [comment]
LGTM also, but I don't have write permissions for this repo.

**Comment by bhs** [comment]
@malafeev now you do :)  https://github.com/opentracing-contrib/java-jdbi/invitations

**Comment by malafeev** [comment]
thanks @bhs

**Pull request merged**
