### PR TITLE
Add Opentracing Jdbi3 Plugin

### LINKED ISSUE #17: Make this a JDBI3 Plugin
Having a JDBI3 plugin makes the usage much simpler:

Be sure to call `Jdbi.installPlugins()` upon initialization and all requests will be traced.

The plugin can have a `customizeJdbi` method that adds the JDBI3 timing collector to the configuration.

### PR DESCRIPTION
**Pull request by sjoerdtalsma**
A JdbiPlugin can be automatically detected and makes using the library even easier.

This fixes #17

### CODE REVIEW

**Comment by sjoerdtalsma** [comment]
Plugin added.
To do:
- [ ] Add unit tests
- [ ] Add documentation

**Comment by malafeev** [comment]
@sjoerdtalsma I'm waiting for README and tests.

**Comment by sjoerdtalsma** [comment]
@malafeev I have added README and tests

Do you know of a way to trick java to believe that a particular class just isn't on the classpath to test the yet-uncovered lines?

**Comment by malafeev** [comment]
thanks @sjoerdtalsma 
trick with classpath is always trick :)

**Pull request merged**
