### PR TITLE
Split JDBI and JDBI3 code in separate modules

### LINKED ISSUE #16: Separate java-jdbi3 module?
Should we make this contrib repo a multi-module repository to release separate
- `jdbi-opentracing` and
- `jdbi3-opentracing` 

maven artifacts?

The split package structure kind of feels 'wrong' and I think having JDBI as **provided** dependency also feels wrong. JDBI is a transient dependency for this module and ought to be declared as such.

I'm willing to create a PR for this if there is demand for it.

### PR DESCRIPTION
**Pull request by sjoerdtalsma**
The split package structure kind of feels 'wrong'.

Having JDBI as provided dependency also feels wrong. JDBI is a transient dependency for this module and ought to be declared as such.

This resolves #16 and #18

### CODE REVIEW

**Comment by sjoerdtalsma** [comment]
@malafeev Could you please review this PR?

I could do a squashed rebase commit if you like, but for now I left the separate commits; they may offer some insight in the steps taken 😉 .

**Comment by malafeev** [comment]
thanks @sjoerdtalsma 
I will release a new version today.

**Comment by sjoerdtalsma** [comment]
@malafeev a release would be great. Should I provide the plugin PR first though?

**Comment by sjoerdtalsma** [comment]
Ah never mind, too late 😉

**Pull request merged**
